server {
    server_name azuracast.luziferase.de stream.luziferase.de luziferase.de;
    
    # Block IPs
    if ($blocked_ip) {
        return 403;
    }
    
    # Block User-Agents
    if ($blocked_agent) {
        return 403;
    }
    
    # Block Pfade
    location ~ (wp-content|\.php$|xyn\.php) {
        return 403;
    }
    
    location = /css/stations/style.css {
        alias /opt/artist-upload/public/css/stations/luziferase.css;
        access_log off;
        add_header Content-Type text/css;
    }
    
    location / {
        # Change to remote server IP and HTTPS port
        proxy_pass http://127.0.0.1:8080;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Skip SSL verification (since 65.21.244.212:8443 likely has self-signed cert)
        proxy_ssl_verify off;
        proxy_ssl_session_reuse on;
        
        client_max_body_size 500M;
    }     

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/luziferase.de/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/luziferase.de/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;


}

server {

    # Block IPs
    if ($blocked_ip) {
        return 403;
    }
    
    # Block User-Agents
    if ($blocked_agent) {
        return 403;
    }
    
    # Block Pfade
    location ~ (wp-content|\.php$|xyn\.php) {
        return 403;
    }


    if ($host = luziferase.de) {
        return 301 https://$host$request_uri;
    }
    if ($host = stream.luziferase.de) {
        return 301 https://$host$request_uri;
    }
    if ($host = azuracast.luziferase.de) {
        return 301 https://$host$request_uri;
    }
        
    client_max_body_size 500M;
    
    listen 80;
    server_name azuracast.luziferase.de stream.luziferase.de luziferase.de;
    return 404;
}